# NOTE: do not name me "config.yml" to avoid conflict with fairseq defaults

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${exp_name}-${now:%H-%M-%S}
exp_name: 'wav2vec_readout_fp_break-seg'
use_only_break_index: True
wav_path: '/home/jhlee/TOBI/wav/'
val_ratio: 0.1  # Ratio of training set to use for timit validation
train_percent: 1.0 # Percentage of training data to use
num_workers: 1
base_ckpt_path: '/home/jhlee/TOBI/model_save/pretrained/wav2vec_small.pt'
# '/home/jhlee/TOBI/model_save/pretrained/hubert_base_ls960.pt'
# '/home/jhlee/TOBI/model_save/pretrained/wav2vec_small.pt'
test_ckpt_path: '/home/jhlee/TOBI/phoneme_seg/outputs/2023-02-14/wav2vec_readout_pho-seg-23-05-40/model.ckpt'
seed: 42
mode: readout
label_dist_threshold: 1 # 20ms tolerance
print_interval: 50 # Train batches to print loss stats
val_interval: 500 # Train batches to eval step
optim_type: adam
beta1: 0.9
beta2: 0.999
momentum: 0.9
weight_decay: 0
pos_weight: 1.0 # BCE loss weighting
epochs: 5
batch_size: 1
lr: 0.001
device: 'cuda:3'
fp16: True # Use mixed precision training
