# saved model_path
model_path: "model_save/phoneme_xlm_epoch=16-val_loss=0.17.ckpt"

# data & model module
pretrained_model: "xlm-roberta-base"
batch_size: 8
num_workers: 1
data_type: "phoneme"
train_file: "processed/train.json"
validation_file: "processed/val.json"
test_file: "processed/test.json"

# trainer
accelerator: "auto"
devices: [2]
max_epochs: 1
accumulate_grad_batches: 4
seed: 1234

# wandb logger
project: TOBI
name: token_classification_xlnet_phoneme_cm